// Self-host the latin woff2 subsets the app actually uses, replacing the
// render-blocking Google Fonts <link>. Fetches the css2 API with a modern
// Chrome UA (so Google serves woff2), keeps only the `latin` subset of each
// @font-face, downloads the files into public/fonts/, and emits a local
// @font-face stylesheet. No build dependency — just curl-equivalent fetch.
import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

// Only the weights actually referenced in the app.
const FAMILIES = [
  { name: "Anton", weights: [400] },
  { name: "Archivo", weights: [600, 700, 800, 900] },
  { name: "Inter", weights: [400, 500, 600, 700] },
];

// src/fonts/ (not public/) so Vite hashes + rebases the URLs for BOTH the
// GitHub Pages sub-path (/tyson2/) and the Vercel root (/) automatically.
const OUT_DIR = new URL("../src/fonts/", import.meta.url);
const slug = (s) => s.toLowerCase().replace(/\s+/g, "-");

const cssUrl = () => {
  const fam = FAMILIES.map(
    (f) => `family=${encodeURIComponent(f.name)}:wght@${f.weights.join(";")}`
  ).join("&");
  return `https://fonts.googleapis.com/css2?${fam}&display=swap`;
};

// Parse the css2 response. Each @font-face is preceded by a `/* subset */`
// comment. Keep only `latin`. Return [{family, weight, url}].
function parseLatin(css) {
  const out = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const subset = m[1];
    if (subset !== "latin") continue;
    const block = m[2];
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const url = /url\(([^)]+)\)\s*format\('woff2'\)/.exec(block)?.[1];
    if (family && weight && url) out.push({ family, weight, url });
  }
  return out;
}

// Fetch one face into memory and hash it, so variable fonts (which Google serves
// as the SAME file for every requested weight) can be detected and deduped.
async function fetchFace(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`download ${url} -> ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return { buf, hash: createHash("md5").update(buf).digest("hex") };
}

const faceBlock = (family, weight, file) =>
  [
    "@font-face {",
    `  font-family: "${family}";`,
    "  font-style: normal;",
    `  font-weight: ${weight};`,
    "  font-display: swap;",
    `  src: url("./fonts/${file}") format("woff2");`,
    "}",
    "",
  ];

const main = async () => {
  await mkdir(OUT_DIR, { recursive: true });
  const res = await fetch(cssUrl(), { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`css fetch ${res.status}`);
  const css = await res.text();
  const faces = parseLatin(css);
  if (!faces.length) throw new Error("no latin faces parsed");

  // Download + hash every face in parallel, then group requested weights by
  // family (Promise.all preserves request order, so grouping is deterministic).
  const fetched = await Promise.all(
    faces.map(async (f) => ({ ...f, ...(await fetchFace(f.url)) }))
  );
  const byFamily = new Map();
  for (const f of fetched) {
    if (!byFamily.has(f.family)) byFamily.set(f.family, []);
    byFamily.get(f.family).push({ weight: Number(f.weight), buf: f.buf, hash: f.hash });
  }

  const lines = [
    "/* Self-hosted latin subsets — replaces the render-blocking Google Fonts CDN.",
    "   Generated by scripts/fetch-fonts.mjs. Variable families (Google serves one",
    "   file for every weight) collapse to a single file + a 100–900 weight range;",
    "   single-weight families ship one file. font-display: swap. */",
    "",
  ];

  for (const [family, list] of byFamily) {
    const oneFile = new Set(list.map((x) => x.hash)).size === 1;
    if (list.length > 1 && oneFile) {
      // Variable font: ship it once with the full weight range.
      const file = `${slug(family)}.woff2`;
      await writeFile(new URL(file, OUT_DIR), list[0].buf);
      lines.push(...faceBlock(family, "100 900", file));
      console.log(`✓ ${file} (variable — ${list.length} weights → 100 900)`);
    } else {
      // Single weight, or genuinely distinct static instances.
      for (const x of list) {
        const file = `${slug(family)}-${x.weight}.woff2`;
        await writeFile(new URL(file, OUT_DIR), x.buf);
        lines.push(...faceBlock(family, x.weight, file));
        console.log(`✓ ${file}`);
      }
    }
  }

  await writeFile(new URL("../src/fonts.css", import.meta.url), lines.join("\n"));
  console.log(`\nWrote src/fonts.css for ${byFamily.size} families`);
};

main().catch((e) => {
  console.error("FONT FETCH FAILED:", e.message);
  process.exit(1);
});
